name: "JiraLinkdePullRequestaction"
description: "Check the PR Name and adds Labels"
inputs:
  title: # id of input
    description: "the PR Title"
    required: true
  JIRA_Token:
     description: "the Token to access the JIRA API"
    required: true
outputs:
  time: # output will be available to future steps
    description: "The current time after waiting"
runs:
  using: "node16"
  main: "dist/index.js"
