name: "JiraLinkdePullRequestaction"
description: "Check the PR Name and adds Labels"
inputs:
  owner:
    description: "the github owner"
    required: true
  repo:
    description: "the github repo"
    required: true
  pr_number:
    description: "the PR number"
    required: true
  github_token:
    description: "the github token"
    required: true
  jira_token:
    description: "the Token to access the JIRA API"
    required: true
  jira_tickets:
    description: "the Jira ticket list to update"
    required: true
  jira_url_Api:
    required: true
  configuration-path:
    description: "The path for the milestone configurations"
    default: ".github/milestone.yml"
  silent:
    description: "Be silent in case of any failure"
    default: false
outputs:
  milestone: # output will be available to future steps
    description: "The milestone number to set"
runs:
  using: "node16"
  main: "dist/index.js"
