name: "JiraLinkdePullRequestaction"
description: "Check the PR Name and adds Labels"
inputs:
  owner:
    description: "the github owner"
    required: true
  repo:
    description: "the github repo"
    required: true
  pr_number:
    description: "the PR number"
    required: true
  github_token:
    description: "the github token"
    required: true
  jira_token:
    description: "the Token to access the JIRA API"
    required: true
  jira_tickets:
    description: "the Jira ticket list to update"
    required: true
outputs:
  time: # output will be available to future steps
    description: "The current time after waiting"
runs:
  using: "node16"
  main: "dist/index.js"
