name: "units-test"
on:
  pull_request:
    types: [opened, reopened, synchronize]

  # test action works running from the graph
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: extracteur
        id: extracter
        uses: sindva/extract-jira-tickets-from-pr-title@1.0.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: uses this action
        id: reader
        uses: ./
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          pr_number: ${{ github.event.number }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          jira_token: ${{ secrets.JIRA_TOKEN }}
          jira_tickets: ${{steps.extracter.outputs.JIRA_TICKETS}}
      - name: get Api url
        uses: ./
        with:
          jira_url_Api: https://support.apps.darva.com/rest/api/2/issue/SINAPPSHAB-
      - name: update milestone
        run: |
          curl --request PATCH \
          --url ${{ github.event.pull_request.issue_url }} \
          --header 'authorization: token ${{ secrets.ACTION_GITHUB_TOKEN }}' \
          --data '{"title":"6789-the revenge", "milestone": ${{steps.reader.outputs.milestone}}}'
