name: "units-test"
on:
  pull_request:
    types: [opened, reopened, synchronize, edited]

  # test action works running from the graph
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - name: extracteur
        id: extracter
        uses: sindva/extract-jira-tickets-from-pr-title@1.0.4
        with:
          url_DCKPIC: http://sinappsird-pic-pr-xxx.dckpic.apps.darva.com/core/auth/login
          urlTicket: https://support.apps.darva.com/browse/SINAPPSHAB-
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: uses this action
        id: reader
        uses: ./
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          pr_number: ${{ github.event.number }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          jira_token: ${{ secrets.JIRA_TOKEN }}
          jira_tickets: ${{steps.extracter.outputs.JIRA_TICKETS}}
          jira_url_Api: https://support.apps.darva.com/rest/api/2/issue/SINAPPSHAB-
      - name: Pull Request Milestone
        uses: iyu/actions-milestone@v1.2.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/milestone.yml
          silent: true
