name: "units-test"
on:
  pull_request:
    types: [opened, reopened, synchronize, edited]

  # test action works running from the graph
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - name: extracteur
        id: extracter
        uses: sindva/extract-jira-tickets-from-pr-title@1.0.4
        with:
          url_DCKPIC: http://sinappsird-pic-pr-xxx.dckpic.apps.darva.com/core/auth/login
          urlTicket: https://support.apps.darva.com/browse/SINAPPSHAB-
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: JiraTransitionner
        uses: tuanddd/jira-automate-transition@v1.0.5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          column-to-move-to-when-review-requested: À CONTRÔLER (PR)
          column-to-move-to-when-changes-requested: En DEV
          column-to-move-to-when-merged: Terminé
          jira-endpoint: https://support.apps.darva.com/rest/api/2/issue
          jira-account: yannick.serra@darva.com
          jira-token: ${{ secrets.JIRA_TOKEN }}
          jira-issue-id: SINAPPSHAB-8948
      - name: uses this action
        id: reader
        uses: ./
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          pr_number: ${{ github.event.number }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          jira_token: ${{ secrets.JIRA_TOKEN }}
          jira_tickets: ${{steps.extracter.outputs.JIRA_TICKETS}}
          jira_url_Api: https://support.apps.darva.com/rest/api/2/issue/SINAPPSHAB-
      - name: update milestone
        run: |
          curl --request PATCH \
          --url ${{ github.event.pull_request.issue_url }} \
          --header 'authorization: token ${{ secrets.ACTION_GITHUB_TOKEN }}' \
          --data '{"title":"6789-the revenge", "milestone": ${{steps.reader.outputs.milestone}}}'
